/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

/**
 *
 * @author user
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        btnEmpleados = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnVenta = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        btnCompra = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        btnProductos = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        btnMateriaPrima = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        panelCompra1 = new frontend.PanelCompra();
        panelMateriaPrima1 = new frontend.PanelMateriaPrima();
        panelProductos1 = new frontend.PanelProductos();
        panelVenta1 = new frontend.PanelVenta();
        panelEmpleados1 = new frontend.PanelEmpleados();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TecRabbit");
        setMinimumSize(new java.awt.Dimension(1500, 800));

        jPanel1.setBackground(new java.awt.Color(13, 12, 12));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(57, 54, 54));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 679));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("U");
        jPanel2.add(jLabel3);

        jSeparator11.setForeground(new java.awt.Color(57, 54, 54));
        jSeparator11.setToolTipText("");
        jSeparator11.setMaximumSize(new java.awt.Dimension(32767, 40));
        jSeparator11.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel2.add(jSeparator11);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User: Administrador");
        jPanel2.add(jLabel2);

        jSeparator10.setForeground(new java.awt.Color(57, 54, 54));
        jSeparator10.setToolTipText("");
        jSeparator10.setMaximumSize(new java.awt.Dimension(32767, 40));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel2.add(jSeparator10);

        btnEmpleados.setBackground(new java.awt.Color(54, 52, 52));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setText("Empleados");
        btnEmpleados.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmpleados);

        jSeparator1.setForeground(new java.awt.Color(57, 54, 54));
        jSeparator1.setToolTipText("");
        jSeparator1.setMaximumSize(new java.awt.Dimension(32767, 40));
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel2.add(jSeparator1);

        btnVenta.setBackground(new java.awt.Color(54, 52, 52));
        btnVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnVenta.setText("Venta");
        btnVenta.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnVenta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnVenta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });
        jPanel2.add(btnVenta);

        jSeparator6.setForeground(new java.awt.Color(57, 54, 54));
        jSeparator6.setToolTipText("");
        jSeparator6.setMaximumSize(new java.awt.Dimension(32767, 40));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel2.add(jSeparator6);

        btnCompra.setBackground(new java.awt.Color(54, 52, 52));
        btnCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnCompra.setText("Compra");
        btnCompra.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnCompra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnCompra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });
        jPanel2.add(btnCompra);

        jSeparator7.setForeground(new java.awt.Color(57, 54, 54));
        jSeparator7.setToolTipText("");
        jSeparator7.setMaximumSize(new java.awt.Dimension(32767, 40));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel2.add(jSeparator7);

        btnProductos.setBackground(new java.awt.Color(54, 52, 52));
        btnProductos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setText("Productos");
        btnProductos.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnProductos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnProductos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel2.add(btnProductos);

        jSeparator8.setForeground(new java.awt.Color(57, 54, 54));
        jSeparator8.setToolTipText("");
        jSeparator8.setMaximumSize(new java.awt.Dimension(32767, 40));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel2.add(jSeparator8);

        btnMateriaPrima.setBackground(new java.awt.Color(54, 52, 52));
        btnMateriaPrima.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMateriaPrima.setForeground(new java.awt.Color(255, 255, 255));
        btnMateriaPrima.setText("Materia Prima");
        btnMateriaPrima.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnMateriaPrima.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnMateriaPrima.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaPrimaActionPerformed(evt);
            }
        });
        jPanel2.add(btnMateriaPrima);

        jSeparator9.setForeground(new java.awt.Color(57, 54, 54));
        jSeparator9.setToolTipText("");
        jSeparator9.setMaximumSize(new java.awt.Dimension(32767, 150));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel2.add(jSeparator9);

        btnSalir.setBackground(new java.awt.Color(243, 221, 133));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir);

        jPanel1.add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel3.setLayout(new java.awt.CardLayout());

        panelCompra1.setVisible(false);
        jPanel3.add(panelCompra1, "card3");

        panelMateriaPrima1.setVisible(true);
        jPanel3.add(panelMateriaPrima1, "card4");

        panelProductos1.setVisible(true);
        jPanel3.add(panelProductos1, "card5");

        panelVenta1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        panelVenta1.setVisible(true);
        jPanel3.add(panelVenta1, "card6");

        panelEmpleados1.setVisible(false);
        jPanel3.add(panelEmpleados1, "card6");

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        InicioSesion login = new InicioSesion();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
       
        panelEmpleados1.show();
        panelEmpleados1.setLocation(0, 0);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        panelVenta1.show();
        panelVenta1.setLocation(0, 0);
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        panelCompra1.show();
        panelCompra1.setLocation(0, 0);
    }//GEN-LAST:event_btnCompraActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        panelProductos1.show();
        panelProductos1.setLocation(0, 0);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaPrimaActionPerformed
        panelMateriaPrima1.show();
        panelMateriaPrima1.setLocation(0, 0);
    }//GEN-LAST:event_btnMateriaPrimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnMateriaPrima;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVenta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private frontend.PanelCompra panelCompra1;
    private frontend.PanelEmpleados panelEmpleados1;
    private frontend.PanelMateriaPrima panelMateriaPrima1;
    private frontend.PanelProductos panelProductos1;
    private frontend.PanelVenta panelVenta1;
    // End of variables declaration//GEN-END:variables
}
